name: work-flows-events

on: push

jobs: 
    echo-hello:
        runs-on: ubuntu-latest
        steps: 
            - name: Show Triggered Event
              run: echo "This workflow was triggered by a ${{ github.event_name }} event."
            