name: 03-workflows-runners

on : push

jobs: 
    ubuntu-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello
              run: |
                echo "SHOWING THE OS"
                echo "OS: $RUNNER_OS"
    windows-hello:
        runs-on: windows-latest
        steps:
            - name: Echo Hello
              shell: bash
              run: |
                echo "SHOWING THE OS"
                echo "OS: $RUNNER_OS"
    